all: demo01 demo02 demo03
demo01: demo01.cpp
	g++ -o demo01 demo01.cpp -g
demo02: demo02.cpp
	g++ -o demo02 demo02.cpp -g
demo03: demo03.cpp
	g++ -o demo03 demo03.cpp -g
clean: 
	rm -f demo01 demo02 demo03